
for lang in AZEBSA  CEBRPV  HAEBSE  HAUCLV  ILORPV  INZNTV  INZSHL  INZTSI  JAVNRF
do
    make get_data DATASET=epitran LANGUAGE=${lang}
done

for lang in BNGWTC TIRUBS BNGBBS HNDSKV
do
    make get_data DATASET=epitran LANGUAGE=${lang}
done

for lang in AZEBSA   HAUCLV  INZNTV  JAVNRF  LAOUBS  RONBSR  SPNBDA  SPNR95  SWESFV  TGKIBT  TRKWTC  CEBRPV  INZSHL  KAZKAZ  MARWTC  RUSS76  SPNDHH  SPNWTC  TCVWTC  TGLPBS  TPIPNG  VIEVOV BNGCLV  HAEBSE  ILORPV  INZTSI  KMRUBS  POLNCV  SOMSIM  SPNNVI  SWESFB  TCWWTC  THATSV  TRKBST  ZLMAVB
do
    make get_data DATASET=epitran LANGUAGE=${lang}
done
