
# Key error: FIZTBL KTBBSE KXCBSE
# Mapping: GURIBS AWAWTC AVNWBT SRIWBT GVLABT PBIWYI GAGIB1 SBLTBL ANNWBT SILGIL GAGIBT SRMWBT PWWTBS SBANVV TUOWBT ATQLAI GO1TBL ADJWBT
# Missing Punctuation: AK1BSG BISBSP
# Alignment error: HAKTHV FRNPDV BQJATB KNFWYI EUSEAB
# Large lexicon issues:  CGCTBL BLTEPI

for lang in \
    BWUTBL SRNBSS MVJWBT HNEBGC \
    NEWNCL JMCBST \
    QVSTBL \
    ACUTBL  BAVWBT  BUSSIM  COKWBT  ESENTM  GUQLPY  INZTSI  KIJPNG  LAOUBS  MCOTBL  MOGLAI  \
    NHUWBT  PAMPBS  QUWHLE  SNNWBT  TIKWYI  URYAOV ADETBL  BBOBSB  BWQBSB  CONWBT  ESSWYI   IPIPNG  \
    KJBSBG  LASABT  MCPWBT  MOPWBT  NHWTBL  PAUUBS  QUYSBU  SNWWBT  TIRUBS  VIEVOV ADHBSU  BCLBPV  \
    CRHIBT  GUXABB  IRIWYI  KJEWBT  LAWNTM  MCQTBL  MORBSS  NHXNTV  PBBWBT  QUZPBS  \
    SOMSIM  TLBLAI  VMWBSM  BCWWBT  BZHPNG  CRNWBT  EWEBSG  GVCTBL  IRKBST  KJHIBT  LEEWBT  \
    MCUTBL  MPGABT  NHYTBL  PBCBSS  QVCTBL  SOYSIM  TLJWBT  VUNBST AEUWBT  BEHWBT  BZJBSW  CSKATB  \
    EWEIBS  ITVSTP  KKIBST  LEFTBL  MDAWBT  MPMTBL  NIAIBS   QVMTBL  SPNBDA  TMCBIV  \
    WMWWYI AGNWPS  BEPLAI  CA1WBT  CSOTBL  FALTBL  GWRWBT  IX1WBT  KKJWBT  LEMWBT  MDYBSE  MPXPNG  \
    NIJLAI  PCMTSC  QVNLLB  SPNDHH  TNATBL  XALIBT AGRTBL  BEXWBT  CAAWBT  CT1TEV  FARWBT  GYMWBT  \
    IXIWBT  KLENLI  LEWLAI  MEJTBL  MQBWBT  NIMBST  PESTPV  QVOVAA  SPNNVI  TOBBSA  XEDWYI AGUNVS  \
    BFABSS  CABNVS  CTUBSM  FIJBSP  GYRSBB  IXLWBT  KMAWBT  LEXWBT  MENBSL  MQJLAI  NINWYI  PIRWBT  \
    SPNR95  TOCTBL  XMMLAI AHKTBS  BFDWBT  CACSBG  CUCTBL  FINV38  HAEBSE  JACWBT  KMHKOV  LGGBSU  \
    MEQWBT  MRWNVS  NKOWBT  PISWBT  QVWTBL  SPNWTC  TOHSBM  XO2IBS AIAWYI  BFOBSB  CAKSBG  CUIWBT  \
    HAGGIL  JAISBG  KMRUBS  LHUTBS  MF1WBT  MSYPNG  NLCLAI  PKBBTL  QVZWBT  SPPTBL  TOSTBL  XOGBSU  \
    BGRBBS  CAPSBB  CUKNVS  FLMUBS  JAMBSW  KNETBL  LIABSL  MFEBSM  MUHWBT  NMZWSB  PLSWYI  QWHLLB  \
    SPYWBT  TPIPNG  XRBWBT AKEBSS  BHZLAI  CARBSS  CWEPBT  FONBSB  HATSBH  JAVNRF  LIPWBT  MFIWYI  \
    MUPNLL  NNBBSU  PLWWBT  QXHWBT  TPMWBT  XSBWYI AKPWBT  BIBWBT  CAXSBB  CWTATB  FRDWBT  HAUCLV  \
    JBUIBS  KNJSBI  LJPLAI  MFKABC  MURTBL  NNWWBT  PMFNTM  QXNWBT  TPPTBL  XSMBFV ALJOMF  BIMWBT  \
    CBSBSP  CYAAVV  FRNPDC  HAYBST  JICWBT  KNKBSL  LLNABT  MFQABT  MUYWBT  NODWBT  POEWYI  QXRBSE  \
    TPTTBL  XSMWBT ALPWBT  CBTTBL  DA1EST  HEHBST  JIVAIE  KNOBSL  LMEABT  MFYWBT  MVCNVS  \
    NOGIBT  POHBSG  REJLAI  STNBSP  TRKBST  XSRWBT ALSBSA  BIVWBT  CBVTBL  DA2WST  FUFPBT  HIFBSP  \
    KOGWBT  LNDBSM  MFZBSS  NOTTBL  POHPOC  RIMBST  SUACLV  TRKWTC  XSUMEV ALTIBT  BJVWYI  \
    CCESBM  DAAWYI  FUQWBT  HIGTBL  JUNWIN  KPVIBT  LOBBSB  MGDBSS  MVPLAI  NPLWYI  POITBL  RMORAM  \
    SUNIBS  TRSUTI  XTDTBL ALZBSU  BKVWYI  CEBRPV  DAHPNG  HILHPV  JVNTBL  KPZBSU  LOKLBT  \
    MGOWYI  MWVLAI  NPYLAI  POLNCV  RMYCVV  SURIBS  TS1BSM  XTMTBL AMFSIM   CEGNTP  DBQWYI  \
    HNDSKV  KAAIBT  KQETBL  LONBSM  MHIBSU  MWWHDV  NSUWBT  PORARA  RONBSR  SUSPBT  TSZBSM  \
    XUOWBT AMKWBT  BLZLAI  DESWBT  GBILAI  KABCEB  KQPWBT  LSIBSM  MHMBSB  MXBMVR  \
    NTMWBT  PORARC  RUGWBT  SUZWBT  TTCWBT  YAZTBL  BMQBSM  CHEIBT  DGABSG  GDEWBT  HNNOMF  \
    KACUBS  KQYBSE  LSMBSU  MHMCAT  MXTTBL  NTRWBT  PORBSP  RUNBSB  SWESFB  TTRIBT  YCLNVS \
    ANVWBT  BMVCAB  CHNUN1  DGIABB  GEJBS2  HNSWBT  KAOABM  KRCLIO  LTNNVV  MHXBSM  MYBABT  NUJWBT  \
    PORNLH  RUSS76  SWESFV  TU1TBL  YUASBM APDAS2  BNGBBS  CHVIBT  DIKTBL  GILBSP  HTOWBT  KAQTBL  \
    KRINVS  LUCHLA  MHYLAI  MYKWBT  NUSBSS  PPKLAI  SAGCAR  SXNLAI  TUEWBT  YUHSBV APRWBT  BNGCLV  \
    CHZWBT  DJKWBT  GKNIBS  HUBWBT  KAZKAZ  KRJWBT  LWOWBT  MIBTBL  MYXBSU  NWBWBT  PRFWBT  SASLAI  \
    TAJWBT  TUFWYI  ZLMAVB ARBIBS  BNGWTC  CJPTJV  DOMBEC  GMVTBL  HUIPNG  KBPRCV  KRUFMP  MAASAV  \
    MIFWBT  MYYWBT  NYFBTL  PRSGNN  TAQWBT  ZYPWBT ARZVDV  BOATBL  CK1WBT  DOPBSB  \
    GNGWYI  HUSLLB  KBRSIM  KSBBST  MAASJV  MILTBL  MZAWBT  NYNBSU  PSELAI  SBDABB  TBYLAI  TWBOMF \
    ATGWYI  BOJWBT  CKIWBT  DSHBTL  GNWNTM  HUUTBL  KCGWBT  MADIBS  MINLAI  MZKTBL  NYOBSU  \
    PTULAI  TBZBSB  TWULAI  BOVWBT  CKKWBT  DTPBSM  HUVTBL  KD1BSU  KTJWBT  \
    MAGSSI  MIOWBT  MZMWBT  NYYBST  PUISMV  SDALAI  TCATBL  TXATBL AVAIBT  BOXWYI  CKOGIL  DTSABM  \
    GOFTBL  IBATIV  KDCPBT  KUBTBL  MAHWGM  MIQSBN  NANTTV  NZIBSG  SEHBSM  TCCBST  TXUTBL \
    BPRWYI  CKWNVS  DUGBTL  GOGBST  ICRWYI  KDIBSU  KUEPNG  MAIWBT  MITTBL  NASPNG  OBOWBT  \
    PXMBSM  SEYWBT  TCVWTC  TYVIBT AVUWBT  BPSWPS  CLETBL  DWRTBL  GORLAI  IFAWBT  KDJBSU  KUMIBT  \
    MAJTBL  MIYWYI  NCHTBL  OJ1CBS  QEJLLB  SGBTBL  TCWWTC  TZBSBM  BQCSIM  CMEWBT  DYIIBS  \
    GQRWBT  IFBTBL  KDNBSZ  KUSTBL  MAKLAI  MJSWTC  NCJTBL  OKUWYI  QU1LSM  SGWBSE  TEMBSL  TZCSBM \
    AWBTBL  CMOWBT  DYOBSG  GSOCAR  IFEWBT  KEKIBS  KVNWBT  MAMSBG  MLGEIV  NCUWBT  OLDBST  \
    QUBPBS  SHIRBD  TEOBSU  TZESBM AYMBSB  BQPSIM  CMRWBT  DYUBSB  GU1WBT  IFKTBL  KEKSBG  KWIWBT  \
    MARWTC  MLGRCV  NDZWBT  OM1TBL  QUCBLA  SHKBSS  TERTBL  TZHSBM AYMSBU  BRUNXB  CNHBSM  DYUWYI  \
    GUBWBT  IFUWPS  KENWBT  MAWWBT  MLGRPV  NEBWYI  ORYWTC  QUFLLB  SHPTBL  TFRWBT  TZTWBT \
    AZEBSA  BSSWBT  CNIWBT  EKAWYI  GUDBSC  IFYWBT  KEOBSU  KYCPNG  MAZTBL  MLYBSM  OSSIBT  \
    QUHRBV  SIGWBT  TGKIBT  UDMIBT AZGTBL  BTDLAI  CNKBSM  EMPWYI  GUGRPV  IGNSBB  KERABT  KYFWBT  \
    MBBWPS  MMSBSG  NFRIBS  OTETBL  QUHSBB  TGLPBS  UDUSIM AZZTBL  BTSLAI  CNLTBL  EN1NIV  \
    GUHWBT  ILORPV  KEZLCN  KYQWYI  MBTWBT  MNBTBL  NGUTBL  OZMTBL  QUJPMC  SJATBL  TGOTBL  UI1UMK \
    BAKIBT  BTTPDT  CNMRGB  ENBBTL  GUISBU  INBWBT  KHKMUB  KYZWBT  MCAWYI  MNFCAB  NH1NMV  PABTBL  \
    QULSBB  SLDTBL  TGPWBT  URATBL BAMLSB  BTXLAI  CNTTBL  ENXBSP  GUMTBL  INZNTV  KIABSC  KZFLAI  \
    MCBTBL  MNKBSG  NHETBL  PADTBL  QUPTBL  SMLTBL  THATSV  URBWBT BANIBS  BUDIBS  COEWBT  ERVWTC  \
    GUOWBT  INZSHL  KIAWBT  LAJBSU  MCDTBL  MOAWBT  NHIWBT  PAGPBS  QUTIBS  SMOBSP  THKBTL  URDWTC
do
    make get_data DATASET=unitran LANGUAGE=${lang}
done
